### ISSUE TITLE
Investigate Codenvy JIRA plugin on JIRA 7.1.9

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#684]
We need to investigate a possible problem with our JIRA plugin and Codenvy system when using Codenvy 4.6+ with JIRA 7.1.9.

Documentation for what the plugin should do is [here](http://codenvy.readme.io/docs/issue-management). You can see the plugin work as intended [here](https://www.youtube.com/watch?v=y4wdplYj6qs).

The customer seems to have correctly installed and configured the plugin but there are two problems:
1. The develop and review links are not showing up in JIRA as links, only as text.
2. The develop and review factories are not being created with the local branch named for the JIRA issue.

Actions:
- Fork the https://github.com/stour/codenvy-jira-plugin repo to the Codenvy repo
- Setup a JIRA 7.1.9 local install (the plugin doesn't work with cloud-based JIRA systems)
- Follow the documentation to setup the plugin
- Determine if the plugin behaves as expected (it should do everything shown in the video)
- For any issues identified, create them in GitHub, estimate them and add link them to this issue.

Resources:
Codenvy JIRA plugin (runs in JIRA): https://github.com/stour/codenvy-jira-plugin
- This should be forked to the Codenvy repository so that we can maintain it going forward.
JIRA addon (runs in codenvy): https://github.com/codenvy/codenvy-jira-addon
GitHub webhook (runs in codenvy): https://github.com/stour/plugin-webhooks

**Comment by vkuznyetsov** [comment]
We are working on creation a similar infrastructure and then will try to reproduce this issue.

**Comment by mkuznyetsov** [comment]
With Jira plugin configured, exception will occur on Issue creation: 

```
2016-09-16 14:57:02,708 http-nio-8080-exec-5 ERROR admin 897x2874x1 1jmjfam 193.108.249.4,127.0.0.1 /secure/QuickCreateIssue.jspa [c.a.event.internal.AsynchronousAbleEventDispatcher] There was an exception
thrown trying to dispatch event [com.atlassian.jira.event.issue.IssueEvent@50dc036c[issue=TEST-4,comment=<null>,worklog=<null>,changelog=<null>,eventTypeId=1,sendMail=true,params={eventsource=workflow, base
url=http://jira.codenvy-stg.com},subtasksUpdated=false]] from the invoker [SingleParameterMethodListenerInvoker{method=public void com.codenvy.jira.IssueCreatedListener.onIssueEvent(com.atlassian.jira.event
.issue.IssueEvent), listener=com.codenvy.jira.IssueCreatedListener@6cad5cba}]
java.lang.RuntimeException: com.atlassian.jira.event.issue.IssueEvent.getUser()Lcom/atlassian/crowd/embedded/api/User;
        at com.atlassian.event.internal.SingleParameterMethodListenerInvoker.invoke(SingleParameterMethodListenerInvoker.java:54)
...
caused by: java.lang.NoSuchMethodError: com.atlassian.jira.event.issue.IssueEvent.getUser()Lcom/atlassian/crowd/embedded/api/User;
        at com.codenvy.jira.IssueCreatedListener.onIssueEvent(IssueCreatedListener.java:128)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        ... 247 more
```

Plugin needs to be updated in order to work with Jira 7.1.9:
https://github.com/codenvy/codenvy-jira-addon

However, plugin is not working properly in it's current state in master branch (1.0.3-SNAPSHOT) - exception occur either on plugin enabling, or going to "Codenvy Administration" page.

**Comment by bmicklea** [comment]
@mkuznyetsov can you link the PR that fixes this here and close the issue if it's complete?

**Comment by mkuznyetsov** [comment]
Plugin has been fixed by this PR:
https://github.com/codenvy/codenvy-jira-addon/pull/8
so it is fixed in new 1.0.4 version

Also, startPoint functionality had to be fixed in Che
https://github.com/eclipse/che/pull/2619
And it will work in 5.0.0-M5 version of Codenvy

**Comment by bmicklea** [comment]
Thanks
